import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 16,
    paddingBottom: 15,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  backButtonRow: {
    marginRight: 8,
    padding: 4,
  },
  locationPicker: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginRight: 10,
  },
  locationLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  notificationBell: {
    padding: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    position: 'relative',
  },
  bellDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  searchBoxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    marginHorizontal: 16,
    marginTop: 15,
    marginBottom: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 20,
  },
  searchBarInput: {
    flex: 1,
    fontSize: 15,
    color: '#1E293B',
    fontWeight: '500',
    padding: 0,
  },
  bannersSlider: {
    marginVertical: 10,
    paddingLeft: 16,
  },
  bannerCard: {
    width: width - 32,
    height: 150,
    borderRadius: 24,
    flexDirection: 'row',
    padding: 20,
    marginRight: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  bannerTextCol: {
    flex: 1,
    justifyContent: 'center',
  },
  bannerBrand: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  bannerTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 22,
    marginBottom: 10,
  },
  bannerBadgeContainer: {
    alignSelf: 'flex-start',
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  bannerBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#004AAD',
  },
  bannerImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginLeft: 10,
  },
  dotContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 8,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#CBD5E1',
    marginHorizontal: 3,
  },
  dotActive: {
    width: 16,
    backgroundColor: '#004AAD',
  },
  categoriesRow: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 15,
  },
  categoryItem: {
    alignItems: 'center',
    width: 75,
  },
  categoryCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  categoryName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 10,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
  },
  filterOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#004AAD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  filterBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#004AAD',
  },
  specialOffersRow: {
    paddingLeft: 16,
    paddingBottom: 15,
  },
  specialCard: {
    width: 170,
    backgroundColor: 'white',
    borderRadius: 20,
    marginRight: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
  },
  specialImg: {
    width: '100%',
    height: 110,
    backgroundColor: '#F1F5F9',
  },
  discountBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#10B981',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  discountBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '800',
  },
  specialInfo: {
    padding: 10,
  },
  specialTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 2,
  },
  specialRest: {
    fontSize: 10,
    fontWeight: '500',
    color: '#94A3B8',
    marginBottom: 6,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  specialPrice: {
    fontSize: 13,
    fontWeight: '800',
    color: '#004AAD',
    marginRight: 6,
  },
  specialOriginal: {
    fontSize: 10,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  restaurantVerticalList: {
    paddingHorizontal: 16,
    gap: 16,
  },
  restRowCard: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  restLogoImg: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F1F5F9',
    alignSelf: 'center',
  },
  restRowInfo: {
    flex: 1,
    marginLeft: 15,
    justifyContent: 'center',
  },
  restRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  restRowName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1E293B',
    flex: 1,
    marginRight: 8,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1E293B',
    marginLeft: 3,
  },
  pillsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
    marginTop: 2,
  },
  pillBox: {
    borderWidth: 1.5,
    borderColor: '#004AAD',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: '#F0F9FF',
  },
  pillLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#004AAD',
  },
  restPriceDetails: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
});
